### ISSUE TITLE
Use LESS and BEM

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/itchy-cordova#23]
We had agreed, on the desktop client, to use LESS with the [BEM](https://getbem.com) methodology. We should also use both here.

**Comment by micahlt** [comment]
Sounds good - I'm behind on school right now, but I'll see if I can squeeze in some time.  😬

**Comment by AyzansAlt** [comment]
Why not SCSS or Sass?

**Comment by locness3** [comment]
We had already done this discussion somewhere in the desktop client's issues (tidyness 100)

**Comment by micahlt** [comment]
+1

**Comment by AyzansAlt** [comment]
++1

**Comment by locness3** [comment]
Changing priority as I think it's more "urgent" than profile and project pages.

**Comment by micahlt** [comment]
@locness3 I'd strongly disagree!  We've got a large audience on Scratch waiting for the Play Store release of this app.  Getting all user-facing features working is key!

**Comment by AyzansAlt** [comment]
someone spend your 20$ and we can all go home

**Comment by locness3** [comment]
Why didn't you use SASS and BEM in the first place, though?

And if we go too fast (and don't use a framework btw) we'll just end up with a spaghetti mess that somehow works but won't be able to be understood by ppl willing to contribute. Let's take our time to make something clean that people can help on - especially considering we have a kind of large community that could do a lot

**Comment by micahlt** [comment]
@locness3 I didn't use SASS in the first place because I was attempting to develop with PhoneGap and there was no good way to work in the browser (unlike Cordova's `run browser`).  I agree we should take our time, but for the initial release we can save time by not integrating a framework.  I also don't understand how having a _specialized_ framework is going to help contributors.  If anything, it'll hurt them because they'll have to take time to learn the framework instead of being able to jump right in.  In fact, I don't have a lot of faith in the developer community we have right now for one reason.  We have several open issues and over 20 people on the SC4 team.  However, no one besides you and me has made any significant contribution.

**Comment by locness3** [comment]
> there was no good way to work in the browser

How does that impact on using LESS? 🤔

**Comment by locness3** [comment]
_Locked and limited conversation to collaborators_

**Comment by locness3** [comment]
>  However, no one besides you and me has made any significant contribution.

Maybe because we're not allowing them to? (let's not get off-topic - reply to this on Teams)

**Comment by locness3** [comment]
@micahlt Please do this, it shouldn't take much time

**Comment by micahlt** [comment]
@locness3 It shouldn't and it's quite simple.  This makes it a primary candidate for a Hacktoberfest participant or another, _less busy_, person on the SC4 team.  😄

**Comment by locness3** [comment]
fair

**Comment by AyzansAlt** [comment]
umm

**Comment by locness3** [comment]
We should get this done asap, at least BEM which would improve the code quality a lot and make it better for someone to help out.

**Comment by micahlt** [comment]
@locness3 True.  How about we split this into two issues, as these aren't directly related and don't have to be done at the same time?

**Comment by locness3** [comment]
ok

**Comment by Dawntraoz** [comment]
Hi @locness3 , @micahlt I see your proposal on DEV, I have experience migrating from CSS to LESS and SASS preprocessors, and I used BEM a lot in the past since TailwindCSS appears in my life hahahaha
So I think I can help you, let me know if you want to have a call or something to show me how it is done now. Otherwise I can just take a look myself, when I have your approval to do it :)

**Comment by locness3** [comment]
@Dawntraoz go ahead, feel free to make a PR! Shouldn't really be hard to do this anyways ;)

~~why didn't you do it @micahlt~~

**Comment by micahlt** [comment]
@locness3 I didn't do this because 1) it's Hacktoberfest and 2) I literally have five minutes a day to work on Itchy, because I'm working and doing school all day long, seven days a week.
